// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/v1/todo.proto

package todov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TodoStatus represents the lifecycle state of a todo
type TodoStatus int32

const (
	TodoStatus_TODO_STATUS_UNSPECIFIED TodoStatus = 0
	TodoStatus_TODO_STATUS_PENDING     TodoStatus = 1
	TodoStatus_TODO_STATUS_IN_PROGRESS TodoStatus = 2
	TodoStatus_TODO_STATUS_COMPLETED   TodoStatus = 3
	TodoStatus_TODO_STATUS_ARCHIVED    TodoStatus = 4
)

// Enum value maps for TodoStatus.
var (
	TodoStatus_name = map[int32]string{
		0: "TODO_STATUS_UNSPECIFIED",
		1: "TODO_STATUS_PENDING",
		2: "TODO_STATUS_IN_PROGRESS",
		3: "TODO_STATUS_COMPLETED",
		4: "TODO_STATUS_ARCHIVED",
	}
	TodoStatus_value = map[string]int32{
		"TODO_STATUS_UNSPECIFIED": 0,
		"TODO_STATUS_PENDING":     1,
		"TODO_STATUS_IN_PROGRESS": 2,
		"TODO_STATUS_COMPLETED":   3,
		"TODO_STATUS_ARCHIVED":    4,
	}
)

func (x TodoStatus) Enum() *TodoStatus {
	p := new(TodoStatus)
	*p = x
	return p
}

func (x TodoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TodoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_todo_proto_enumTypes[0].Descriptor()
}

func (TodoStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_todo_proto_enumTypes[0]
}

func (x TodoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TodoStatus.Descriptor instead.
func (TodoStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{0}
}

// TodoPriority represents urgency level
type TodoPriority int32

const (
	TodoPriority_TODO_PRIORITY_UNSPECIFIED TodoPriority = 0
	TodoPriority_TODO_PRIORITY_LOW         TodoPriority = 1
	TodoPriority_TODO_PRIORITY_MEDIUM      TodoPriority = 2
	TodoPriority_TODO_PRIORITY_HIGH        TodoPriority = 3
	TodoPriority_TODO_PRIORITY_CRITICAL    TodoPriority = 4
)

// Enum value maps for TodoPriority.
var (
	TodoPriority_name = map[int32]string{
		0: "TODO_PRIORITY_UNSPECIFIED",
		1: "TODO_PRIORITY_LOW",
		2: "TODO_PRIORITY_MEDIUM",
		3: "TODO_PRIORITY_HIGH",
		4: "TODO_PRIORITY_CRITICAL",
	}
	TodoPriority_value = map[string]int32{
		"TODO_PRIORITY_UNSPECIFIED": 0,
		"TODO_PRIORITY_LOW":         1,
		"TODO_PRIORITY_MEDIUM":      2,
		"TODO_PRIORITY_HIGH":        3,
		"TODO_PRIORITY_CRITICAL":    4,
	}
)

func (x TodoPriority) Enum() *TodoPriority {
	p := new(TodoPriority)
	*p = x
	return p
}

func (x TodoPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TodoPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_todo_proto_enumTypes[1].Descriptor()
}

func (TodoPriority) Type() protoreflect.EnumType {
	return &file_api_proto_v1_todo_proto_enumTypes[1]
}

func (x TodoPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TodoPriority.Descriptor instead.
func (TodoPriority) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{1}
}

// Todo represent a task item
type Todo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status      TodoStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=todo.v1.TodoStatus" json:"status,omitempty"`
	Priority    TodoPriority           `protobuf:"varint,5,opt,name=priority,proto3,enum=todo.v1.TodoPriority" json:"priority,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	// Tags for categorization
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	OwnerId       string                 `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,9,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	TenantId      string                 `protobuf:"bytes,10,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int64                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"` // Optimistic locking version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetStatus() TodoStatus {
	if x != nil {
		return x.Status
	}
	return TodoStatus_TODO_STATUS_UNSPECIFIED
}

func (x *Todo) GetPriority() TodoPriority {
	if x != nil {
		return x.Priority
	}
	return TodoPriority_TODO_PRIORITY_UNSPECIFIED
}

func (x *Todo) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Todo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Todo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Todo) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Todo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Todo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Todo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Todo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// CreateTodoRequest creates a new todo
type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      TodoPriority           `protobuf:"varint,4,opt,name=priority,proto3,enum=todo.v1.TodoPriority" json:"priority,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,7,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTodoRequest) GetPriority() TodoPriority {
	if x != nil {
		return x.Priority
	}
	return TodoPriority_TODO_PRIORITY_UNSPECIFIED
}

func (x *CreateTodoRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *CreateTodoRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTodoRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

type CreateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoResponse) Reset() {
	*x = CreateTodoResponse{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoResponse) ProtoMessage() {}

func (x *CreateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type GetTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoResponse) Reset() {
	*x = GetTodoResponse{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoResponse) ProtoMessage() {}

func (x *GetTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoResponse.ProtoReflect.Descriptor instead.
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *GetTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type UpdateTodoRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Id       string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Fields to update (following Google API design)
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Todo       *Todo                  `protobuf:"bytes,4,opt,name=todo,proto3" json:"todo,omitempty"`
	// Version for optimistic locking
	Version       int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTodoRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTodoRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateTodoRequest) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

func (x *UpdateTodoRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoResponse) Reset() {
	*x = UpdateTodoResponse{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoResponse) ProtoMessage() {}

func (x *UpdateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

// DeleteTodoRequest soft-deletes a todo
type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTodoRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DeleteTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoResponse) Reset() {
	*x = DeleteTodoResponse{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoResponse) ProtoMessage() {}

func (x *DeleteTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoResponse.ProtoReflect.Descriptor instead.
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTodoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListTodosRequest with filtering, sorting, and pagination
type ListTodosRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Pagination
	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Filtering
	StatusFilter     []TodoStatus   `protobuf:"varint,4,rep,packed,name=status_filter,json=statusFilter,proto3,enum=todo.v1.TodoStatus" json:"status_filter,omitempty"`
	PriorityFilter   []TodoPriority `protobuf:"varint,5,rep,packed,name=priority_filter,json=priorityFilter,proto3,enum=todo.v1.TodoPriority" json:"priority_filter,omitempty"`
	TagsFilter       []string       `protobuf:"bytes,6,rep,name=tags_filter,json=tagsFilter,proto3" json:"tags_filter,omitempty"`
	AssignedToFilter string         `protobuf:"bytes,7,opt,name=assigned_to_filter,json=assignedToFilter,proto3" json:"assigned_to_filter,omitempty"`
	// Date range filtering
	DueDateFrom *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=due_date_from,json=dueDateFrom,proto3" json:"due_date_from,omitempty"`
	DueDateTo   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=due_date_to,json=dueDateTo,proto3" json:"due_date_to,omitempty"`
	// Sorting
	SortBy    string    `protobuf:"bytes,10,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // e.g., "created_at", "due_date", "priority"
	SortOrder SortOrder `protobuf:"varint,11,opt,name=sort_order,json=sortOrder,proto3,enum=todo.v1.SortOrder" json:"sort_order,omitempty"`
	// Search query (full-text search on title/description)
	SearchQuery   string `protobuf:"bytes,12,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{9}
}

func (x *ListTodosRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListTodosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTodosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTodosRequest) GetStatusFilter() []TodoStatus {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListTodosRequest) GetPriorityFilter() []TodoPriority {
	if x != nil {
		return x.PriorityFilter
	}
	return nil
}

func (x *ListTodosRequest) GetTagsFilter() []string {
	if x != nil {
		return x.TagsFilter
	}
	return nil
}

func (x *ListTodosRequest) GetAssignedToFilter() string {
	if x != nil {
		return x.AssignedToFilter
	}
	return ""
}

func (x *ListTodosRequest) GetDueDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDateFrom
	}
	return nil
}

func (x *ListTodosRequest) GetDueDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDateTo
	}
	return nil
}

func (x *ListTodosRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListTodosRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

func (x *ListTodosRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{10}
}

func (x *ListTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *ListTodosResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// UpdateTodoStatusRequest handles state transitions
type UpdateTodoStatusRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Metadata  *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Id        string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NewStatus TodoStatus             `protobuf:"varint,3,opt,name=new_status,json=newStatus,proto3,enum=todo.v1.TodoStatus" json:"new_status,omitempty"`
	// Optional reason for status change (audit trail)
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Version for optimistic locking
	Version       int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoStatusRequest) Reset() {
	*x = UpdateTodoStatusRequest{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoStatusRequest) ProtoMessage() {}

func (x *UpdateTodoStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTodoStatusRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateTodoStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTodoStatusRequest) GetNewStatus() TodoStatus {
	if x != nil {
		return x.NewStatus
	}
	return TodoStatus_TODO_STATUS_UNSPECIFIED
}

func (x *UpdateTodoStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateTodoStatusRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateTodoStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoStatusResponse) Reset() {
	*x = UpdateTodoStatusResponse{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoStatusResponse) ProtoMessage() {}

func (x *UpdateTodoStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTodoStatusResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

// BatchCreateTodosRequest for bulk operations
type BatchCreateTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Requests      []*CreateTodoRequest   `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateTodosRequest) Reset() {
	*x = BatchCreateTodosRequest{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateTodosRequest) ProtoMessage() {}

func (x *BatchCreateTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateTodosRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateTodosRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{13}
}

func (x *BatchCreateTodosRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BatchCreateTodosRequest) GetRequests() []*CreateTodoRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	Errors        []*ErrorDetail         `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateTodosResponse) Reset() {
	*x = BatchCreateTodosResponse{}
	mi := &file_api_proto_v1_todo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateTodosResponse) ProtoMessage() {}

func (x *BatchCreateTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_todo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateTodosResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateTodosResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_todo_proto_rawDescGZIP(), []int{14}
}

func (x *BatchCreateTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *BatchCreateTodosResponse) GetErrors() []*ErrorDetail {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_api_proto_v1_todo_proto protoreflect.FileDescriptor

const file_api_proto_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/todo.proto\x12\atodo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x19api/proto/v1/common.proto\"\xe2\x03\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.todo.v1.TodoStatusR\x06status\x121\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x15.todo.v1.TodoPriorityR\bpriority\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12\x1f\n" +
	"\vassigned_to\x18\t \x01(\tR\n" +
	"assignedTo\x12\x1b\n" +
	"\ttenant_id\x18\n" +
	" \x01(\tR\btenantId\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\r \x01(\x03R\aversion\"\xa0\x02\n" +
	"\x11CreateTodoRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.todo.v1.RequestMetadataR\bmetadata\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x15.todo.v1.TodoPriorityR\bpriority\x125\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1f\n" +
	"\vassigned_to\x18\a \x01(\tR\n" +
	"assignedTo\"7\n" +
	"\x12CreateTodoResponse\x12!\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoR\x04todo\"V\n" +
	"\x0eGetTodoRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.todo.v1.RequestMetadataR\bmetadata\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"4\n" +
	"\x0fGetTodoResponse\x12!\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoR\x04todo\"\xd3\x01\n" +
	"\x11UpdateTodoRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.todo.v1.RequestMetadataR\bmetadata\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12!\n" +
	"\x04todo\x18\x04 \x01(\v2\r.todo.v1.TodoR\x04todo\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"7\n" +
	"\x12UpdateTodoResponse\x12!\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoR\x04todo\"Y\n" +
	"\x11DeleteTodoRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.todo.v1.RequestMetadataR\bmetadata\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\".\n" +
	"\x12DeleteTodoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xad\x04\n" +
	"\x10ListTodosRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.todo.v1.RequestMetadataR\bmetadata\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x128\n" +
	"\rstatus_filter\x18\x04 \x03(\x0e2\x13.todo.v1.TodoStatusR\fstatusFilter\x12>\n" +
	"\x0fpriority_filter\x18\x05 \x03(\x0e2\x15.todo.v1.TodoPriorityR\x0epriorityFilter\x12\x1f\n" +
	"\vtags_filter\x18\x06 \x03(\tR\n" +
	"tagsFilter\x12,\n" +
	"\x12assigned_to_filter\x18\a \x01(\tR\x10assignedToFilter\x12>\n" +
	"\rdue_date_from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vdueDateFrom\x12:\n" +
	"\vdue_date_to\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdueDateTo\x12\x17\n" +
	"\asort_by\x18\n" +
	" \x01(\tR\x06sortBy\x121\n" +
	"\n" +
	"sort_order\x18\v \x01(\x0e2\x12.todo.v1.SortOrderR\tsortOrder\x12!\n" +
	"\fsearch_query\x18\f \x01(\tR\vsearchQuery\"h\n" +
	"\x11ListTodosResponse\x12#\n" +
	"\x05todos\x18\x01 \x03(\v2\r.todo.v1.TodoR\x05todos\x12.\n" +
	"\tpage_info\x18\x02 \x01(\v2\x11.todo.v1.PageInfoR\bpageInfo\"\xc5\x01\n" +
	"\x17UpdateTodoStatusRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.todo.v1.RequestMetadataR\bmetadata\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x122\n" +
	"\n" +
	"new_status\x18\x03 \x01(\x0e2\x13.todo.v1.TodoStatusR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"=\n" +
	"\x18UpdateTodoStatusResponse\x12!\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoR\x04todo\"\x87\x01\n" +
	"\x17BatchCreateTodosRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.todo.v1.RequestMetadataR\bmetadata\x126\n" +
	"\brequests\x18\x02 \x03(\v2\x1a.todo.v1.CreateTodoRequestR\brequests\"m\n" +
	"\x18BatchCreateTodosResponse\x12#\n" +
	"\x05todos\x18\x01 \x03(\v2\r.todo.v1.TodoR\x05todos\x12,\n" +
	"\x06errors\x18\x02 \x03(\v2\x14.todo.v1.ErrorDetailR\x06errors*\x94\x01\n" +
	"\n" +
	"TodoStatus\x12\x1b\n" +
	"\x17TODO_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TODO_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TODO_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15TODO_STATUS_COMPLETED\x10\x03\x12\x18\n" +
	"\x14TODO_STATUS_ARCHIVED\x10\x04*\x92\x01\n" +
	"\fTodoPriority\x12\x1d\n" +
	"\x19TODO_PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TODO_PRIORITY_LOW\x10\x01\x12\x18\n" +
	"\x14TODO_PRIORITY_MEDIUM\x10\x02\x12\x16\n" +
	"\x12TODO_PRIORITY_HIGH\x10\x03\x12\x1a\n" +
	"\x16TODO_PRIORITY_CRITICAL\x10\x042\x96\x04\n" +
	"\vTodoService\x12E\n" +
	"\n" +
	"CreateTodo\x12\x1a.todo.v1.CreateTodoRequest\x1a\x1b.todo.v1.CreateTodoResponse\x12<\n" +
	"\aGetTodo\x12\x17.todo.v1.GetTodoRequest\x1a\x18.todo.v1.GetTodoResponse\x12E\n" +
	"\n" +
	"UpdateTodo\x12\x1a.todo.v1.UpdateTodoRequest\x1a\x1b.todo.v1.UpdateTodoResponse\x12E\n" +
	"\n" +
	"DeleteTodo\x12\x1a.todo.v1.DeleteTodoRequest\x1a\x1b.todo.v1.DeleteTodoResponse\x12B\n" +
	"\tListTodos\x12\x19.todo.v1.ListTodosRequest\x1a\x1a.todo.v1.ListTodosResponse\x12W\n" +
	"\x10UpdateTodoStatus\x12 .todo.v1.UpdateTodoStatusRequest\x1a!.todo.v1.UpdateTodoStatusResponse\x12W\n" +
	"\x10BatchCreateTodos\x12 .todo.v1.BatchCreateTodosRequest\x1a!.todo.v1.BatchCreateTodosResponseB5Z3github.com/dmehra2102/TaskForge/api/proto/v1;todov1b\x06proto3"

var (
	file_api_proto_v1_todo_proto_rawDescOnce sync.Once
	file_api_proto_v1_todo_proto_rawDescData []byte
)

func file_api_proto_v1_todo_proto_rawDescGZIP() []byte {
	file_api_proto_v1_todo_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_todo_proto_rawDesc), len(file_api_proto_v1_todo_proto_rawDesc)))
	})
	return file_api_proto_v1_todo_proto_rawDescData
}

var file_api_proto_v1_todo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_v1_todo_proto_goTypes = []any{
	(TodoStatus)(0),                  // 0: todo.v1.TodoStatus
	(TodoPriority)(0),                // 1: todo.v1.TodoPriority
	(*Todo)(nil),                     // 2: todo.v1.Todo
	(*CreateTodoRequest)(nil),        // 3: todo.v1.CreateTodoRequest
	(*CreateTodoResponse)(nil),       // 4: todo.v1.CreateTodoResponse
	(*GetTodoRequest)(nil),           // 5: todo.v1.GetTodoRequest
	(*GetTodoResponse)(nil),          // 6: todo.v1.GetTodoResponse
	(*UpdateTodoRequest)(nil),        // 7: todo.v1.UpdateTodoRequest
	(*UpdateTodoResponse)(nil),       // 8: todo.v1.UpdateTodoResponse
	(*DeleteTodoRequest)(nil),        // 9: todo.v1.DeleteTodoRequest
	(*DeleteTodoResponse)(nil),       // 10: todo.v1.DeleteTodoResponse
	(*ListTodosRequest)(nil),         // 11: todo.v1.ListTodosRequest
	(*ListTodosResponse)(nil),        // 12: todo.v1.ListTodosResponse
	(*UpdateTodoStatusRequest)(nil),  // 13: todo.v1.UpdateTodoStatusRequest
	(*UpdateTodoStatusResponse)(nil), // 14: todo.v1.UpdateTodoStatusResponse
	(*BatchCreateTodosRequest)(nil),  // 15: todo.v1.BatchCreateTodosRequest
	(*BatchCreateTodosResponse)(nil), // 16: todo.v1.BatchCreateTodosResponse
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
	(*RequestMetadata)(nil),          // 18: todo.v1.RequestMetadata
	(*fieldmaskpb.FieldMask)(nil),    // 19: google.protobuf.FieldMask
	(SortOrder)(0),                   // 20: todo.v1.SortOrder
	(*PageInfo)(nil),                 // 21: todo.v1.PageInfo
	(*ErrorDetail)(nil),              // 22: todo.v1.ErrorDetail
}
var file_api_proto_v1_todo_proto_depIdxs = []int32{
	0,  // 0: todo.v1.Todo.status:type_name -> todo.v1.TodoStatus
	1,  // 1: todo.v1.Todo.priority:type_name -> todo.v1.TodoPriority
	17, // 2: todo.v1.Todo.due_date:type_name -> google.protobuf.Timestamp
	17, // 3: todo.v1.Todo.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: todo.v1.Todo.updated_at:type_name -> google.protobuf.Timestamp
	18, // 5: todo.v1.CreateTodoRequest.metadata:type_name -> todo.v1.RequestMetadata
	1,  // 6: todo.v1.CreateTodoRequest.priority:type_name -> todo.v1.TodoPriority
	17, // 7: todo.v1.CreateTodoRequest.due_date:type_name -> google.protobuf.Timestamp
	2,  // 8: todo.v1.CreateTodoResponse.todo:type_name -> todo.v1.Todo
	18, // 9: todo.v1.GetTodoRequest.metadata:type_name -> todo.v1.RequestMetadata
	2,  // 10: todo.v1.GetTodoResponse.todo:type_name -> todo.v1.Todo
	18, // 11: todo.v1.UpdateTodoRequest.metadata:type_name -> todo.v1.RequestMetadata
	19, // 12: todo.v1.UpdateTodoRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 13: todo.v1.UpdateTodoRequest.todo:type_name -> todo.v1.Todo
	2,  // 14: todo.v1.UpdateTodoResponse.todo:type_name -> todo.v1.Todo
	18, // 15: todo.v1.DeleteTodoRequest.metadata:type_name -> todo.v1.RequestMetadata
	18, // 16: todo.v1.ListTodosRequest.metadata:type_name -> todo.v1.RequestMetadata
	0,  // 17: todo.v1.ListTodosRequest.status_filter:type_name -> todo.v1.TodoStatus
	1,  // 18: todo.v1.ListTodosRequest.priority_filter:type_name -> todo.v1.TodoPriority
	17, // 19: todo.v1.ListTodosRequest.due_date_from:type_name -> google.protobuf.Timestamp
	17, // 20: todo.v1.ListTodosRequest.due_date_to:type_name -> google.protobuf.Timestamp
	20, // 21: todo.v1.ListTodosRequest.sort_order:type_name -> todo.v1.SortOrder
	2,  // 22: todo.v1.ListTodosResponse.todos:type_name -> todo.v1.Todo
	21, // 23: todo.v1.ListTodosResponse.page_info:type_name -> todo.v1.PageInfo
	18, // 24: todo.v1.UpdateTodoStatusRequest.metadata:type_name -> todo.v1.RequestMetadata
	0,  // 25: todo.v1.UpdateTodoStatusRequest.new_status:type_name -> todo.v1.TodoStatus
	2,  // 26: todo.v1.UpdateTodoStatusResponse.todo:type_name -> todo.v1.Todo
	18, // 27: todo.v1.BatchCreateTodosRequest.metadata:type_name -> todo.v1.RequestMetadata
	3,  // 28: todo.v1.BatchCreateTodosRequest.requests:type_name -> todo.v1.CreateTodoRequest
	2,  // 29: todo.v1.BatchCreateTodosResponse.todos:type_name -> todo.v1.Todo
	22, // 30: todo.v1.BatchCreateTodosResponse.errors:type_name -> todo.v1.ErrorDetail
	3,  // 31: todo.v1.TodoService.CreateTodo:input_type -> todo.v1.CreateTodoRequest
	5,  // 32: todo.v1.TodoService.GetTodo:input_type -> todo.v1.GetTodoRequest
	7,  // 33: todo.v1.TodoService.UpdateTodo:input_type -> todo.v1.UpdateTodoRequest
	9,  // 34: todo.v1.TodoService.DeleteTodo:input_type -> todo.v1.DeleteTodoRequest
	11, // 35: todo.v1.TodoService.ListTodos:input_type -> todo.v1.ListTodosRequest
	13, // 36: todo.v1.TodoService.UpdateTodoStatus:input_type -> todo.v1.UpdateTodoStatusRequest
	15, // 37: todo.v1.TodoService.BatchCreateTodos:input_type -> todo.v1.BatchCreateTodosRequest
	4,  // 38: todo.v1.TodoService.CreateTodo:output_type -> todo.v1.CreateTodoResponse
	6,  // 39: todo.v1.TodoService.GetTodo:output_type -> todo.v1.GetTodoResponse
	8,  // 40: todo.v1.TodoService.UpdateTodo:output_type -> todo.v1.UpdateTodoResponse
	10, // 41: todo.v1.TodoService.DeleteTodo:output_type -> todo.v1.DeleteTodoResponse
	12, // 42: todo.v1.TodoService.ListTodos:output_type -> todo.v1.ListTodosResponse
	14, // 43: todo.v1.TodoService.UpdateTodoStatus:output_type -> todo.v1.UpdateTodoStatusResponse
	16, // 44: todo.v1.TodoService.BatchCreateTodos:output_type -> todo.v1.BatchCreateTodosResponse
	38, // [38:45] is the sub-list for method output_type
	31, // [31:38] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_api_proto_v1_todo_proto_init() }
func file_api_proto_v1_todo_proto_init() {
	if File_api_proto_v1_todo_proto != nil {
		return
	}
	file_api_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_todo_proto_rawDesc), len(file_api_proto_v1_todo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_todo_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_todo_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_todo_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_todo_proto_msgTypes,
	}.Build()
	File_api_proto_v1_todo_proto = out.File
	file_api_proto_v1_todo_proto_goTypes = nil
	file_api_proto_v1_todo_proto_depIdxs = nil
}
